=== quyetnv8893/XML_0129/XML_0129_1008_QuyetNV/App_Data/player_management.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="playerManagement">
        <xs:complexType>
            <xs:all>
                <xs:element name="club" minOccurs="1" maxOccurs="1" type="club_type"/>
                <xs:element name="careers">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="career" maxOccurs="unbounded" type="career_type"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="coaches">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="coach" maxOccurs="unbounded" type="coach_type"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="players">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="player" maxOccurs="unbounded" type="player_type"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="achievements">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="achievement" maxOccurs="unbounded"
                                type="achievement_type"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="matches">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="match" maxOccurs="unbounded" type="match_type"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="leagues">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="league" maxOccurs="unbounded" type="league_type"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="players_achievements">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="player_achievement" maxOccurs="unbounded"
                                type="player_achievement_type"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="players_matches">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="player_match" maxOccurs="unbounded"
                                type="player_match_type"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:all>
        </xs:complexType>
        <xs:key name="key-career">
            <xs:selector xpath="careers/career"/>
            <xs:field xpath="id"/>
        </xs:key>
        <xs:key name="key-club">
            <xs:selector xpath="club"/>
            <xs:field xpath="name"/>
        </xs:key>
        <xs:key name="key-coach">
            <xs:selector xpath="coaches/coach"/>
            <xs:field xpath="id"/>
        </xs:key>
        <xs:key name="key-player">
            <xs:selector xpath="players/player"/>
            <xs:field xpath="id"/>
        </xs:key>
        <xs:key name="key-achievement">
            <xs:selector xpath="achievements/achievement"/>
            <xs:field xpath="name"/>
        </xs:key>
        <xs:key name="key-match">
            <xs:selector xpath="matches/match"/>
            <xs:field xpath="id"/>
        </xs:key>
        <xs:key name="key-league">
            <xs:selector xpath="leagues/league"/>
            <xs:field xpath="name"/>
        </xs:key>
        <xs:keyref refer="key-club" name="key-player-club-ref">
            <xs:selector xpath="players/player"/>
            <xs:field xpath="clubName"/>
        </xs:keyref>
        <xs:keyref refer="key-player" name="key-career-player-ref">
            <xs:selector xpath="careers/career"/>
            <xs:field xpath="playerId"/>
        </xs:keyref>
        <xs:keyref refer="key-club" name="key-coach-club-ref">
            <xs:selector xpath="coaches/coach"/>
            <xs:field xpath="clubName"/>
        </xs:keyref>
        <xs:keyref refer="key-league" name="key-match-league-ref">
            <xs:selector xpath="matches/match"/>
            <xs:field xpath="leagueName"/>
        </xs:keyref>
        <xs:keyref refer="key-player" name="key-player_achievement-player-ref">
            <xs:selector xpath="players_achievements/player_achievement"/>
            <xs:field xpath="playerId"/>
        </xs:keyref>
        <xs:keyref refer="key-achievement" name="key-player_achievement-achievement-ref">
            <xs:selector xpath="players_achievements/player_achievement"/>
            <xs:field xpath="achievementName"/>
        </xs:keyref>
        <xs:keyref refer="key-player" name="key-player_match-player-ref">
            <xs:selector xpath="players_matches/player_match"/>
            <xs:field xpath="playerId"/>
        </xs:keyref>
        <xs:keyref refer="key-match" name="key-player_match-match-ref">
            <xs:selector xpath="players_matches/player_match"/>
            <xs:field xpath="matchId"/>
        </xs:keyref>
    </xs:element>
    <xs:complexType name="career_type">
        <xs:all>
            <xs:element name="id" type="xs:string"/>
            <xs:element name="from" type="xs:date"/>
            <xs:element name="to" type="xs:date" nillable="true"/>
            <xs:element name="noOfGoals" type="xs:int"/>
            <xs:element name="playerId" type="xs:string"/>
        </xs:all>
    </xs:complexType>
    <xs:complexType name="club_type">
        <xs:all>
            <xs:element name="name" type="xs:string"/>                            
            <xs:element name="logoLink" type="xs:string"/>
            <xs:element name="foundedDate" type="xs:date"/>
            <xs:element name="stadium" type="xs:string"/>
        </xs:all>
    </xs:complexType>
    <xs:complexType name="coach_type">
        <xs:all>
            <xs:element name="id" type="xs:string"/>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="dateOfBirth" type="xs:date"/>
            <xs:element name="imageLink" type="xs:string"/>
            <xs:element name="position" type="xs:string"/>
            <xs:element name="clubName" type="xs:string"/>
        </xs:all>
    </xs:complexType>
    <xs:complexType name="player_type">
        <xs:all>
            <xs:element name="clubName" type="xs:string"/>
            <xs:element name="id" type="xs:string"/>
            <xs:element name="number" type="xs:int"/>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="position" type="xs:string"/>
            <xs:element name="dateOfBirth" type="xs:date"/>
            <xs:element name="placeOfBirth" type="xs:string"/>
            <xs:element name="weight" type="xs:double"/>
            <xs:element name="height" type="xs:double"/>
            <xs:element name="description" type="xs:string"/>
            <xs:element name="imageLink" type="xs:string"/>
            <xs:element name="status" type="xs:boolean"/>
        </xs:all>
    </xs:complexType>
    <xs:complexType name="achievement_type">
        <xs:all>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="imageLink" type="xs:string"/>
        </xs:all>
    </xs:complexType>
    <xs:complexType name="match_type">
        <xs:all>
            <xs:element name="id" type="xs:string"/>
            <xs:element name="time" type="xs:dateTime"/>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="score" type="xs:string"/>
            <xs:element name="leagueName" type="xs:string"/>
        </xs:all>
    </xs:complexType>
    <xs:complexType name="league_type">
        <xs:all>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="logoLink" type="xs:string"/>
        </xs:all>
    </xs:complexType>
    <xs:complexType name="player_achievement_type">
        <xs:all>
            <xs:element name="number" type="xs:int"/>
            <xs:element name="playerId" type="xs:string"/>
            <xs:element name="achievementName" type="xs:string"/>
        </xs:all>
    </xs:complexType>
    <xs:complexType name="player_match_type">
        <xs:all>
            <xs:element name="noOfGoals" type="xs:int"/>
            <xs:element name="noOfYellows" type="xs:int"/>
            <xs:element name="noOfReds" type="xs:int"/>            
            <xs:element name="playerId" type="xs:string"/>
            <xs:element name="matchId" type="xs:string"/>
        </xs:all>
    </xs:complexType>
  <!--
    <xs:simpleType name="position_type">
        <xs:restriction base="xs:string">
            <xs:enumeration value="CB"/>
            <xs:enumeration value="GK"/>
            <xs:enumeration value="SW"/>
            <xs:enumeration value="LB"/>
            <xs:enumeration value="DM"/>
            <xs:enumeration value="CM"/>
            <xs:enumeration value="AM"/>
            <xs:enumeration value="LW"/>
            <xs:enumeration value="RW"/>
            <xs:enumeration value="WF"/>
            <xs:enumeration value="CF"/>
            <xs:enumeration value="RB"/>
        </xs:restriction>
    </xs:simpleType>
    -->
</xs:schema>

=== quyetnv8893/XML_0129/XML_0129_1008_QuyetNV/App_Data/player_management.xml
<?xml version="1.0" encoding="utf-8"?>
<playerManagement xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://thangpq.fall.vn player_management.xsd">
  <club>
    <name>Real Madrid</name>
    <foundedDate>1902-06-03</foundedDate>
    <logoLink>http://img1.wikia.nocookie.net/__cb20120629123703/uncyclopedia/images/b/bf/Real_Madrid_logo.png</logoLink>
    <stadium>Santiago Bernabeu</stadium>
  </club>
  <players>
    <!-- 1 -->
    <player>
            <clubName>Real Madrid</clubName>
            <id>01</id>
            <number>1</number>
            <name>CASILLAS
                IKER CASILLAS FERNÁNDEZ</name>
            <position>Goalkeeper</position>
            <dateOfBirth>1981-05-20</dateOfBirth>
            <placeOfBirth>Móstoles (Madrid)</placeOfBirth>
            <weight>84</weight>
            <height>1.85</height>
            <description> He has been a Madrid fan since he was a child and he fulfilled his dream of playing for the club at the age of 10. Form the very beginning, it was clear that he was a special goalkeeper with extremely fast reflexes, great strength in both legs and the gift of being almost unbeatable in one-on-one situations.        
                He has proved to be a born leader in all of the teams he has played for both at Real Madrid and for Spain. In his first Champions League Final, he performed brilliantly to help his team win their eighth European Cup. That same season, he played so well that he also won the Bravo Award for the best young player of the year.        
                He has won everything there is to win, both for Real Madrid and for Spain. He was a key player in his country’s victories in the UEFA European Championship in 2008 and 2012 and was one of the Spanish heroes in the FIFA World Cup in South Africa in 2010. FIFA, UEFA, the fans…but, above all, his fantastic saves, honoured him
                with the title of the world’s best goalkeeper for five years running.</description>
            <imageLink>http://i.imgur.com/rkJ35oM.png</imageLink>
            <status>true</status>
    </player>
    <!-- TODO: ADD MORE PLAYERS HERE -->
    <!-- 2 -->
    <player>
      <clubName>Real Madrid</clubName>
      <id>02</id>
      <number>13</number>
      <name>KEYLOR NAVAS
                KEYLOR NAVAS</name>
      <position>Goalkeeper</position>
      <dateOfBirth>1986-12-15</dateOfBirth>
      <placeOfBirth>San Isidro (Costa Rica)</placeOfBirth>
      <weight>78</weight>
      <height>1.85</height>
      <description> He is quick, has great reflexes, always positions himself well and is one of the best in one-to-ones; 
                Keylor Navas has everything it takes to be an exceptional keeper. 
                He demonstrated it in Brazil, where he only let in two goals in five matches and took Costa Rica 
                to the quarter-finals for the first time in their history.</description>
      <imageLink>http://i.imgur.com/rkJ35oM.png</imageLink>
      <status>true</status>
    </player>
    <!-- 3 -->
    <player>
      <clubName>Real Madrid</clubName>
      <id>03</id>
      <number>25</number>
      <name>PACHECO
                FERNANDO PACHECO FLORES</name>
      <position>Goalkeeper</position>
      <dateOfBirth>1992-05-18</dateOfBirth>
      <placeOfBirth>Badajoz</placeOfBirth>
      <weight>81</weight>
      <height>1.86</height>
      <description> An experienced, quietly effective goalkeeper whose excellent reflexes see him shine in one-on-one situations. 
                He made his competitive debut for the first team in a 5-1 win over Ponferradina in the Copa del Rey.</description>
      <imageLink>http://i.imgur.com/rkJ35oM.png</imageLink>
      <status>true</status>
    </player>
    <!-- 4 -->
    <player>
      <clubName>Real Madrid</clubName>
      <id>04</id>
      <number>25</number>
      <name>SERGIO RAMOS
                SERGIO RAMOS GARCÍA</name>
      <position>Defender</position>
      <dateOfBirth>1986-03-30</dateOfBirth>
      <placeOfBirth>Camas (Sevilla, Spain)</placeOfBirth>
      <weight>75</weight>
      <height>1.83</height>
      <description> His courage and strength made him the revelation of La Liga in the 2004/2005 season. 
                He was then playing for Sevilla, where he had started his career at the youth academy. 
                His qualities did not go unnoticed by Real Madrid who signed him that summer.</description>
      <imageLink>http://i.imgur.com/rkJ35oM.png</imageLink>
      <status>true</status>
    </player>
    <!-- 5 -->
    <player>
      <clubName>Real Madrid</clubName>
      <id>05</id>
      <number>3</number>
      <name>PEPE
                KÉPLER LAVERAN LIMA FERREIRA</name>
      <position>Defender</position>
      <dateOfBirth>1983-02-26</dateOfBirth>
      <placeOfBirth>Maceió (Brazil)</placeOfBirth>
      <weight>81</weight>
      <height>1.88</height>
      <description>Pepe is technically impeccable, tactically perfect, has a great sense of positioning, speed, 
                strength and intelligence. 
                He is very strong in the air and is also elegant when playing the ball out of defence. 
                Since he arrived at the club, Pepe has been a vital presence at the heart of the Real Madrid defence.</description>
      <imageLink>http://i.imgur.com/rkJ35oM.png</imageLink>
      <status>true</status>
    </player>
    <!-- 6 -->
    <player>
      <clubName>Real Madrid</clubName>
      <id>06</id>
      <number>2</number>
      <name>VARANE
                RAPHAËL VARANE</name>
      <position>Defender</position>
      <dateOfBirth>1993-04-25</dateOfBirth>
      <placeOfBirth>Lille (France)</placeOfBirth>
      <weight>78</weight>
      <height>1.91</height>
      <description>Varane began his football career at the age of just seven. 
                He showed the first signs of his talent at the Football Training Centre in Liévin (France) 
                and began to develop his outstanding feature as a player, his elegance on the ball. 
                He began to star for the youth teams of Racing Club de Lens and at the age of 17 
                he made his debut for them in Ligue 1, 
                going on to become one of the stars of the 2010-11 season.</description>
      <imageLink>http://i.imgur.com/rkJ35oM.png</imageLink>
      <status>true</status>
    </player>
    <!-- 7 -->
    <player>
      <clubName>Real Madrid</clubName>
      <id>07</id>
      <number>17</number>
      <name>ARBELOA
                ÁLVARO ARBELOA COCA</name>
      <position>Defender</position>
      <dateOfBirth>1983-01-17</dateOfBirth>
      <placeOfBirth>Salamanca</placeOfBirth>
      <weight>79</weight>
      <height>1.84</height>
      <description>Álvaro Arbeloa is a versatile player who is a born leader inside and outside the dressing-room. 
                These are the qualities that made him stand out in the Real Madrid youth team. 
                In 2005 he captained Real Madrid Castilla and was one of the key players in their promotion 
                to the Spanish Second Division, 
                a promotion which had taken 14 years to achieve.</description>
      <imageLink>http://i.imgur.com/rkJ35oM.png</imageLink>
      <status>true</status>
    </player>
    <!-- 8 -->
    <player>
      <clubName>Real Madrid</clubName>
      <id>08</id>
      <number>15</number>
      <name>CARVAJAL
                DANIEL CARVAJAL RAMOS</name>
      <position>Defender</position>
      <dateOfBirth>1992-01-11</dateOfBirth>
      <placeOfBirth>Leganés (Madrid)</placeOfBirth>
      <weight>73</weight>
      <height>1.73</height>
      <description>Local full-back Dani Carvajal started his career at the Real Madrid youth academy 
                and is particularly noted for his speed and the composure he displays in his position. 
                He has been a regular at all level of Spanish international youth football 
                and has earned a European Championship medal at Under -19 and Under-21 level.</description>
      <imageLink>http://i.imgur.com/rkJ35oM.png</imageLink>
      <status>true</status>
    </player>
    <!-- 9 -->
    <player>
      <clubName>Real Madrid</clubName>
      <id>09</id>
      <number>5</number>
      <name>COENTRÃO
                FÁBIO A. SILVA COENTRÃO</name>
      <position>Defender</position>
      <dateOfBirth>1988-03-11</dateOfBirth>
      <placeOfBirth>Vila do Conde (Portugal)</placeOfBirth>
      <weight>70</weight>
      <height>1.79</height>
      <description>Speed, swerves and versatility are the main features of Fábio Coentrão. 
                He is a player who can offer a lot to the team both in attack and in defence 
                and has plenty of experience of football at the highest level. 
                His defensive ability helped Real Madrid to win La Liga and the Spanish Super Cup in 2012.</description>
      <imageLink>http://i.imgur.com/rkJ35oM.png</imageLink>
      <status>true</status>
    </player>
    <!-- 10 -->
    <player>
      <clubName>Real Madrid</clubName>
      <id>10</id>
      <number>12</number>
      <name>MARCELO
                MARCELO VIEIRA DA SILVA</name>
      <position>Defender</position>
      <dateOfBirth>1988-05-12</dateOfBirth>
      <placeOfBirth>Río de Janeiro (Brazil)</placeOfBirth>
      <weight>75</weight>
      <height>1.74</height>
      <description>Marcelo started playing five-a-side football at the age of 9 and by 13 he was at Fluminense. 
                    He comes from quite a poor family and almost had to leave the football academy 
                    because he couldn’t afford to pay for the bus to take him to training. 
                    Nevertheless, his determination and his ability made him fight for what he loved and he was best at: football.</description>
      <imageLink>http://i.imgur.com/rkJ35oM.png</imageLink>
      <status>true</status>
    </player>
    <!-- 11 -->
    <player>
